# Generated by Django 5.2.7 on 2025-10-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServisKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_adi', models.CharField(max_length=255)),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('seri_no', models.CharField(blank=True, max_length=100, null=True)),
                ('aksesuar', models.CharField(blank=True, max_length=255, null=True)),
                ('gelis_tarihi', models.DateField()),
                ('ariza', models.TextField(blank=True, null=True)),
                ('servis_ismi', models.CharField(max_length=255)),
                ('servise_gonderim_tarihi', models.DateField(blank=True, null=True)),
                ('yapilan_islem', models.TextField(blank=True, null=True)),
                ('servisten_gelis_tarihi', models.DateField(blank=True, null=True)),
                ('teslim_tarihi', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
