# Generated by Django 5.2.7 on 2025-11-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Servis Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servis',
                'verbose_name_plural': 'Servisler',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='service_name',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Servis'),
        ),
    ]
