# Generated by Django 5.2.7 on 2025-10-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_serviskayit_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviskayit',
            name='status',
            field=models.CharField(default='Beklemede', max_length=50),
        ),
    ]
