# Generated by Django 5.2.7 on 2025-10-31 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviskayit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServisKayitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degisiklik_tarihi', models.DateTimeField(auto_now_add=True)),
                ('eski_degerler', models.JSONField(null=True)),
                ('yeni_degerler', models.JSONField()),
                ('servis_kayit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='service.serviskayit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
