# Generated by Django 5.2.7 on 2025-10-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_serviskayitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviskayitlog',
            name='changed_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
