# Generated by Django 5.2.7 on 2025-10-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_serviskayitlog_changed_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviskayitlog',
            name='changed_fields',
        ),
    ]
