# Generated by Django 5.2.7 on 2025-10-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_serviskayitlog_changed_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviskayitlog',
            name='eski_degerler',
        ),
        migrations.RemoveField(
            model_name='serviskayitlog',
            name='yeni_degerler',
        ),
        migrations.AddField(
            model_name='serviskayitlog',
            name='changed_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
