# Generated by Django 5.2.7 on 2025-11-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_serviskayitlog_eski_degerler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviskayit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
